### ISSUE TITLE
[BUG]: Jupyter help magic unconverted unicode character

### ISSUE THREAD

**Issue by s-weigand** [spatialaudio/nbsphinx#330]
When using jupyter help magic (`?`), the output gets messed up, since jyputer internally wraps unicode characters around parts of the output to format it.
I think this is why it is also excluded when setting `nbsphinx_execute = "always"`.
The problem should be solvable with a `re.sub()`.

**Expected/Notebook render:**
![expected_output](https://user-images.githubusercontent.com/9513634/66201880-b065d700-e6a4-11e9-856d-fcee97ccaf35.jpg)

**Actual render HTML:**
![wrong_output](https://user-images.githubusercontent.com/9513634/66201863-a217bb00-e6a4-11e9-8838-0376b092d8ac.jpg)

**Actual render PDF:**
![wrong_output_pdf](https://user-images.githubusercontent.com/9513634/66202769-d4c2b300-e6a6-11e9-9c88-824aaaff26d4.jpg)

**Json representation of the cell:**

```json
{
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {
    "tags": [
     "nbval-ignore-output"
    ]
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "\u001b[1;31mDocstring:\u001b[0m\n",
       "%%bash script magic\n",
       "\n",
       "Run cells with bash in a subprocess.\n",
       "\n",
       "This is a shortcut for `%%script bash`\n",
       "\u001b[1;31mFile:\u001b[0m      c:\\anaconda3\\lib\\site-packages\\ipython\\core\\magics\\script.py\n"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "%%bash?"
   ]
  },
```

 - **OS:** Windows 10
 - **Version:** `nbsphinx==0.4.2`

**Comment by mgeier** [comment]
Thanks for the report!

I've known this problem for quite some time already and I've even started working on it on the 
https://github.com/spatialaudio/nbsphinx/compare/ansi-in-text branch (but I think this was the wrong approach).

I hope I can finish this at some point ...

> I think this is why it is also excluded when setting `nbsphinx_execute = "always"`.

Those outputs are generated by JupyterLab.
They are apparently not generated by the Classic Notebook nor by `nbconvert --execute` (which is used in `nbsphinx`).

It's good to see that more people are using JupyterLab and that this problem is finally reported!

----

Unrelated to this issue: I've noticed spurious scroll bars (or rather scroll buttons) in your HTML screenshot.
I normally don't see those, do you also see them on https://nbsphinx.readthedocs.io/en/0.4.3/code-cells.html?
Which browser are you using?
Do you have an idea how to get rid of them?

**Comment by s-weigand** [comment]
The scrollbars are only shown Chrome (not in FireFox) and are displayed due to an overflow caused by [`sphinx-copybutton`](https://github.com/choldgraf/sphinx-copybutton) for single line of code cells.
Still need to investigate, which `css` 'clash' causes it.

**Comment by s-weigand** [comment]
After some playing around, the following `scss` fixed the issue for me:

```scss
div.nbinput div.input_area,
div.nboutput div.output_area {
  padding: 0 !important;
}
div.nbinput,
div.nbinput div.prompt,
div.nbinput div.input_area,
div.nbinput div[class*="highlight"],
div.nbinput div[class*="highlight"] pre,
div.nboutput,
div.nbinput div.prompt,
div.nbinput div.output_area,
div.nboutput div[class*="highlight"],
div.nboutput div[class*="highlight"] pre {
  padding: 0.2em !important;

  a.copybtn {
    width: 0.8em;
    height: 0.8em;
  }
}

a.copybtn {
  padding: 0;
}
```

compiled `css` version:
```css
div.nbinput div.input_area,
div.nboutput div.output_area {
  padding: 0 !important;
}

div.nbinput,
div.nbinput div.prompt,
div.nbinput div.input_area,
div.nbinput div[class*="highlight"],
div.nbinput div[class*="highlight"] pre,
div.nboutput,
div.nbinput div.prompt,
div.nbinput div.output_area,
div.nboutput div[class*="highlight"],
div.nboutput div[class*="highlight"] pre {
  padding: 0.2em !important;
}

div.nbinput a.copybtn,
div.nbinput div.prompt a.copybtn,
div.nbinput div.input_area a.copybtn,
div.nbinput div[class*="highlight"] a.copybtn,
div.nbinput div[class*="highlight"] pre a.copybtn,
div.nboutput a.copybtn,
div.nbinput div.prompt a.copybtn,
div.nbinput div.output_area a.copybtn,
div.nboutput div[class*="highlight"] a.copybtn,
div.nboutput div[class*="highlight"] pre a.copybtn {
  width: 0.8em;
  height: 0.8em;
}

a.copybtn {
  padding: 0;
}
```

Haven't found any buggy outputs for that yet.

**Note:** The `!important` is to overwrite the css from `nbsphinx`.
