### ISSUE TITLE
make CSS agnostic of light/dark schemes

### ISSUE THREAD

**Issue by 2bndy5** [spatialaudio/nbsphinx#734]
I noticed with the furo theme example is the background color for stderr output isn't compatible with the dark scheme:
![image](https://user-images.githubusercontent.com/14963867/235434593-e81c3f6b-30ac-496d-a945-cca5c54d8e44.png)
but using a transparency with slightly increased saturation should remedy that in a consistent way for light or dark schemes:
```css
/* nbsphinx-code-cells.css | https://nbsphinx.readthedocs.io/en/furo-theme/_static/nbsphinx-code-cells.css */

div.nboutput.container div.output_area.stderr {
  /* background: #fdd; */
  background: #e8808075;
}
```
![image](https://user-images.githubusercontent.com/14963867/235434508-b4a9b431-0962-4415-9b0d-17b938ea902f.png)

There are other styles that use opaque hard-coded colors which don't blend well with light and dark schemes. I'll keep updating this thread with other related findings...

**Comment by 2bndy5** [comment]
hardcoded colors that could be made agnostic of BG color:
- https://github.com/spatialaudio/nbsphinx/blob/a619a5091c29815c1605166d6adca26700fae6e9/src/nbsphinx/_static/nbsphinx-code-cells.css_t#L147
- https://github.com/spatialaudio/nbsphinx/blob/a619a5091c29815c1605166d6adca26700fae6e9/src/nbsphinx/_static/nbsphinx-code-cells.css_t#L218
- https://github.com/spatialaudio/nbsphinx/blob/a619a5091c29815c1605166d6adca26700fae6e9/src/nbsphinx/_static/nbsphinx-code-cells.css_t#L224
- https://github.com/spatialaudio/nbsphinx/blob/a619a5091c29815c1605166d6adca26700fae6e9/src/nbsphinx/_static/nbsphinx-code-cells.css_t#L247

The following is subject to #733:
https://github.com/spatialaudio/nbsphinx/blob/a619a5091c29815c1605166d6adca26700fae6e9/src/nbsphinx/_static/nbsphinx-code-cells.css_t#L130

The slider widget's value (text)
![image](https://user-images.githubusercontent.com/14963867/235551645-25618fca-c863-4aeb-85e2-5c223e4263e5.png)
seems to be subject to `ipywidget`'s CSS but can probably be overridden with
```css

/* not deprecated CSS applies to both widget text value and label */
.jupyter-widgets {
  color: inherit;
}


/* ************ widget text values **************** */
/* <DEPRECATED> */
.widget-readout, /* </DEPRECATED> */
.jupyter-widget-readout {
  color: inherit;
}


/* ************ widget labels ********************* */
/* </DEPRECATED> */
.widget-label, /* </DEPRECATED> */
.jupyter-widget-label {
  color: inherit;
}
```
